CAMERA_WIDTH = 320
CAMERA_HEIGHT = 180

DEFAULT_PIXEL_SCALE = 4

TILE_SIZE = 8
LIGHT_MARGIN = 4

MAP_WIDTH = 500
MAP_HEIGHT = 500

SMALL_LIGHT_SIZE = 2.5 * TILE_SIZE
LARGE_LIGHT_SIZE = 4.5 * TILE_SIZE

PLAYER_WIDTH = 8
PLAYER_HEIGHT = 8

PLAYER_MOVE_FRAMES = 12
PLAYER_MINE_FRAMES = 12
PLAYER_COOLDOWN_FRAMES = 10
PLAYER_MOVECOOL_FRAMES = 3

WALL_SPRITE_COLS = 7 * 5
WALL_SPRITE_ROWS = 7 * 2
GEM_SPRITE_COLS = 7
ORE_SPRITE_COLS = 10

PSTATE = {
    idle = 1,
    moving = 2,
    mining = 3,
    cooldown = 4
}