CAMERA_WIDTH = 320
CAMERA_HEIGHT = 180

DEFAULT_PIXEL_SCALE = 4

TILE_SIZE = 8

MAP_WIDTH = CAMERA_WIDTH / TILE_SIZE
MAP_HEIGHT = CAMERA_HEIGHT / TILE_SIZE

SMALL_LIGHT_SIZE = 2.5 * TILE_SIZE
LARGE_LIGHT_SIZE = 4.5 * TILE_SIZE

PLAYER_WIDTH = 8
PLAYER_HEIGHT = 8
PLAYER_MOVE_FRAMES = 10
PLAYER_MINE_FRAMES = 10
PLAYER_COOLDOWN_FRAMES = 3

PSTATE = {
    idle = 1,
    moving = 2,
    mining = 3,
    cooldown = 4
}